"""Criação inicial de todas as tabelas

Revision ID: 33c8fe9175d9
Revises: 
Create Date: 2025-06-11 09:54:52.412299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33c8fe9175d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('numero_casa', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('CPF', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tipo_usuario', mysql.ENUM('Funcionario', 'Cliente'), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_ativo', sa.String(length=6), nullable=True),
    sa.Column('otp_expiracao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('CPF'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agencia',
    sa.Column('id_agencia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('codigo_agencia', sa.String(length=10), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id_endereco'], ),
    sa.PrimaryKeyConstraint('id_agencia'),
    sa.UniqueConstraint('codigo_agencia')
    )
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('score_credito', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('funcionario',
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('codigo_funcionario', sa.String(length=20), nullable=False),
    sa.Column('cargo', mysql.ENUM('Estagiario', 'Atendente', 'Gerente'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_supervisor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_supervisor'], ['funcionario.id_funcionario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_funcionario'),
    sa.UniqueConstraint('codigo_funcionario'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('conta',
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('numero_conta', sa.String(length=20), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tipo_conta', mysql.ENUM('Poupanca', 'Corrente', 'Investimento'), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('status', mysql.ENUM('Ativa', 'Encerrada', 'Bloqueada'), nullable=False),
    sa.Column('id_agencia', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_agencia'], ['agencia.id_agencia'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_conta'),
    sa.UniqueConstraint('numero_conta')
    )
    op.create_table('relatorio',
    sa.Column('id_relatorio', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('tipo_relatorio', sa.String(length=50), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario.id_funcionario'], ),
    sa.PrimaryKeyConstraint('id_relatorio')
    )
    op.create_table('conta_corrente',
    sa.Column('id_conta_corrente', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('limite_cheque_especial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxa_manutencao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id_conta'], ),
    sa.PrimaryKeyConstraint('id_conta_corrente')
    )
    op.create_table('conta_investimento',
    sa.Column('id_conta_investimento', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('perfil_risco', mysql.ENUM('Baixo', 'Medio', 'Alto'), nullable=False),
    sa.Column('valor_minimo_deposito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxa_rendimento_base', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id_conta'], ),
    sa.PrimaryKeyConstraint('id_conta_investimento')
    )
    op.create_table('conta_poupanca',
    sa.Column('id_conta_poupanca', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('taxa_rendimento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ultimo_rendimento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id_conta'], ),
    sa.PrimaryKeyConstraint('id_conta_poupanca')
    )
    op.create_table('transacao',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', mysql.ENUM('Deposito', 'Saque', 'Transferencia', 'Pagamento', 'Rendimento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('id_conta_origem', sa.Integer(), nullable=True),
    sa.Column('id_conta_destino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_conta_destino'], ['conta.id_conta'], ),
    sa.ForeignKeyConstraint(['id_conta_origem'], ['conta.id_conta'], ),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('conta_poupanca')
    op.drop_table('conta_investimento')
    op.drop_table('conta_corrente')
    op.drop_table('relatorio')
    op.drop_table('conta')
    op.drop_table('funcionario')
    op.drop_table('cliente')
    op.drop_table('auditoria')
    op.drop_table('agencia')
    op.drop_table('usuario')
    op.drop_table('endereco')
    # ### end Alembic commands ###
